### PR TITLE
Fix tinkers modifier criteria issues in advancement requirements

### PR DESCRIPTION
**Pull request by Crackerhead22**
Sticky is from certain materials, not a modifier that can be added, Shears is.

### CODE REVIEW

**Comment by Crackerhead22** [comment]
This pull and my other one should close issues [#825](https://github.com/Darkosto/SkyFactory4Issues/issues/825), [569#](https://github.com/Darkosto/SkyFactory4Issues/issues/569), and [#199](https://github.com/Darkosto/SkyFactory4Issues/issues/199) .

**Comment by justinrusso** [comment]
Since you combined a few already, can you just merge #29 's changes into this PR?

**Comment by Crackerhead22** [comment]
How do I merge them?  New to the pull request thing.

**Comment by Crackerhead22** [comment]
@justinrusso I think i merged it right?

**Pull request merged**
